[project]
name = "cad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Smile", email = "156634569+smileBlueRose@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
cad = "cad:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
